<script setup lang="ts">
import { BaseContainer, PublicFooter, PublicHeader } from '@altruisme/ui'

const props = defineProps<{ actionHref: string; actionLabel: string }>()

const symptoms = ['il génère très peu de trafic', 'tu ne sais pas vraiment sur quels mots-clés te positionner', 'certaines pages apparaissent sur Google, mais jamais suffisamment haut', 'tu publies parfois du contenu sans savoir s’il sert réellement à quelque chose', 'ton site présente ton activité, mais génère peu de demandes entrantes', 'tu sais qu’il faudrait travailler ton SEO, mais tu ne sais pas par où commencer', 'tu as déjà lancé Semrush, Ahrefs ou Search Console… sans vraiment savoir quoi faire des données.']
const angles = [
  { title: 'SEO', text: 'Pour que les bonnes personnes puissent te trouver.' },
  { title: 'Produit & conversion', text: 'Pour qu’elles comprennent rapidement ce que tu proposes et pourquoi ça peut les aider.' },
  { title: 'Technique', text: 'Pour identifier les problèmes qui empêchent ton site de performer correctement.' },
]
const audit = [
  { title: 'Positionnement', text: 'Est-ce que Google comprend réellement ce que tu proposes ? Est-ce que tes pages ciblent les bonnes intentions de recherche ? Ton positionnement est-il suffisamment précis pour être identifiable ?' },
  { title: 'Contenu', text: 'Quelles pages méritent d’être retravaillées ? Quels sujets peuvent réellement générer du trafic qualifié ? Quels contenus manquent aujourd’hui ?' },
  { title: 'Structure', text: 'Ton architecture permet-elle aux moteurs de recherche et aux utilisateurs de comprendre facilement ton site ? Le maillage interne soutient-il tes pages importantes ?' },
  { title: 'Technique', text: 'Indexation, performances, balises, erreurs importantes, structure HTML, expérience mobile… Je cherche les problèmes qui ont réellement un impact.' },
  { title: 'Conversion', text: 'Quand quelqu’un arrive sur ton site, comprend-il rapidement qui tu aides, ce que tu proposes, pourquoi il devrait te faire confiance et quelle est la prochaine étape ?' },
]
const deliverables = ['Un diagnostic clair de la situation actuelle.', 'Les principaux freins identifiés.', 'Les opportunités SEO prioritaires.', 'Les pages à retravailler.', 'Les nouveaux contenus à envisager.', 'Les améliorations techniques importantes.', 'Des recommandations concrètes.', 'Une roadmap priorisée sur les 90 prochains jours.']
const before = ['Je sais qu’il faut travailler mon SEO, mais je ne sais pas vraiment quoi faire.', 'Je publie un peu au hasard.', 'Je ne sais pas quelles pages améliorer.', 'Mon site génère très peu de demandes.', 'J’ai plein de données mais aucune priorité.']
const after = ['Tu connais les pages importantes.', 'Tu sais quelles recherches cibler.', 'Tu comprends les principales faiblesses du site.', 'Tu sais quels contenus créer.']
</script>

<template>
  <div class="min-h-screen bg-sand text-ink">
    <PublicHeader product="Builder" :action-href="props.actionHref" :action-label="props.actionLabel" />
    <main>
      <section class="relative overflow-hidden bg-[linear-gradient(125deg,#f7f2e9_0%,#f3ede3_46%,#e4ece8_100%)] py-24 sm:py-36"><div class="pointer-events-none absolute -right-28 top-0 h-[34rem] w-[34rem] rounded-full bg-petrol/14 blur-[145px]" /><BaseContainer><div class="relative max-w-4xl"><p class="text-sm font-semibold uppercase tracking-[.18em] text-petrol">Altruisme Builder</p><h1 class="mt-5 text-5xl font-bold tracking-tight sm:text-7xl">Ton site ne devrait pas simplement exister.</h1><p class="mt-6 text-3xl font-medium text-petrol sm:text-4xl">Il devrait t’apporter des clients.</p><p class="mt-8 max-w-2xl text-lg leading-8 text-muted">Tu as investi du temps dans ton site. Peut-être même beaucoup. Mais aujourd’hui, il ressemble davantage à une carte de visite qu’à un véritable canal d’acquisition.</p><p class="mt-6 max-w-2xl text-lg leading-8 text-muted">Le problème n’est pas forcément ton offre. Ni ton expertise. Souvent, ton site est simplement mal compris par Google, mal structuré pour tes prospects… ou les deux.</p><p class="mt-8 max-w-2xl text-xl font-semibold leading-8">Je t’aide à identifier ce qui bloque, à savoir quoi améliorer en priorité et, si besoin, à l’implémenter.</p><a :href="props.actionHref" class="mt-10 inline-flex rounded-xl bg-petrol px-6 py-3.5 text-sm font-semibold text-white shadow-lg shadow-petrol/20 transition hover:-translate-y-0.5 hover:bg-petrol-hover">{{ props.actionLabel }}</a></div></BaseContainer></section>

      <section class="py-20 sm:py-28"><BaseContainer><div class="max-w-3xl"><p class="text-sm font-semibold uppercase tracking-[.18em] text-petrol">Une approche complète</p><h2 class="mt-4 text-3xl font-bold tracking-tight sm:text-5xl">SEO, produit et technique.</h2><p class="mt-7 text-lg leading-8 text-muted">Je ne viens pas uniquement regarder tes mots-clés.</p></div><div class="mt-12 grid gap-5 md:grid-cols-3"><article v-for="angle in angles" :key="angle.title" class="rounded-3xl border border-petrol/15 bg-white/55 p-7"><h3 class="text-2xl font-bold">{{ angle.title }}</h3><p class="mt-3 leading-7 text-muted">{{ angle.text }}</p></article></div><p class="mt-10 max-w-3xl text-lg leading-8 text-muted">L’objectif n’est pas d’obtenir un rapport SEO de 80 pages.<br /><strong class="text-ink">L’objectif est de savoir quoi faire maintenant.</strong></p></BaseContainer></section>

      <section class="bg-petrol-dark py-20 sm:py-28"><BaseContainer><div class="max-w-3xl"><p class="text-sm font-semibold uppercase tracking-[.18em] text-[#a9c1bd]">Le constat</p><h2 class="mt-4 text-3xl font-bold tracking-tight text-sand-light sm:text-5xl">Peut-être que tu te reconnais.</h2><p class="mt-7 text-lg leading-8 text-[#d8e1de]">Ton site existe depuis plusieurs mois ou plusieurs années. Mais…</p><ul class="mt-8 space-y-3 text-lg text-[#d8e1de]"><li v-for="symptom in symptoms" :key="symptom" class="flex gap-3"><span class="mt-3 h-1.5 w-1.5 shrink-0 rounded-full bg-[#a9c1bd]" />{{ symptom }}</li></ul><p class="mt-10 text-xl font-semibold leading-8 text-sand-light">Et surtout : tu ne veux pas passer les six prochains mois à devenir expert SEO.<br /><span class="text-[#a9c1bd]">Tu veux savoir ce qui bloque. Et quoi faire pour l’améliorer.</span></p></div></BaseContainer></section>

      <section class="py-20 sm:py-28"><BaseContainer><div class="max-w-3xl"><h2 class="text-3xl font-bold tracking-tight sm:text-5xl">Le SEO n’est pas uniquement une histoire de mots-clés.</h2><p class="mt-7 text-lg leading-8 text-muted">Un site peut être parfaitement indexé… et ne générer aucune opportunité.</p><p class="mt-6 text-lg leading-8 text-muted">Parce qu’un bon référencement repose sur plusieurs choses qui fonctionnent ensemble :</p><div class="mt-8 space-y-3 text-2xl font-bold text-petrol"><p>Être trouvé.</p><p>Être compris.</p><p>Donner envie d’aller plus loin.</p></div><p class="mt-8 text-lg leading-8 text-muted">C’est pour ça que je ne regarde jamais le SEO isolément.</p></div></BaseContainer></section>

      <section class="bg-sand-light py-20 sm:py-28"><BaseContainer><div class="grid gap-12 lg:grid-cols-[1fr_.8fr] lg:items-start"><div><p class="text-sm font-semibold uppercase tracking-[.18em] text-petrol">Le coût de l’inaction</p><h2 class="mt-4 text-3xl font-bold tracking-tight sm:text-5xl">Continuer sans stratégie coûte plus cher qu’on ne le pense.</h2><p class="mt-7 text-lg leading-8 text-muted">Le risque n’est pas uniquement de perdre quelques positions sur Google. C’est de continuer à publier les mauvais contenus, retravailler les mauvaises pages, viser des requêtes que personne ne recherche et laisser passer chaque mois des prospects qui cherchent déjà ce que tu proposes.</p></div><div class="rounded-[2rem] border border-petrol/15 bg-white/60 p-8"><p class="text-xl font-bold">Le SEO prend du temps.</p><p class="mt-4 text-lg leading-8 text-muted">Autant investir ce temps au bon endroit.</p></div></div></BaseContainer></section>

      <section class="py-20 sm:py-28"><BaseContainer><div class="max-w-3xl"><p class="text-sm font-semibold uppercase tracking-[.18em] text-petrol">Une autre façon d’auditer</p><h2 class="mt-4 text-3xl font-bold tracking-tight sm:text-5xl">Pourquoi les audits SEO classiques finissent souvent dans un dossier Drive.</h2><p class="mt-7 text-lg leading-8 text-muted">127 erreurs détectées. 43 pages à optimiser. 26 Core Web Vitals. 18 backlinks suspects. Puis une énorme checklist.</p><p class="mt-8 text-2xl font-bold">« Très bien. Je commence par quoi lundi matin ? »</p><p class="mt-8 text-lg leading-8 text-muted">C’est précisément le problème que mon Sprint SEO cherche à résoudre.</p><h3 class="mt-14 text-3xl font-bold">Moins de recommandations. Plus de priorités.</h3><p class="mt-5 text-lg leading-8 text-muted">Je préfère identifier <strong class="text-ink">5 actions importantes</strong> que te donner une liste de 75 optimisations que tu ne feras jamais.</p></div><div class="mt-12 grid gap-5 md:grid-cols-3"><article v-for="(step, index) in [{title:'Comprendre',text:'Ton activité, tes clients, ton marché et le rôle que ton site doit réellement jouer.'},{title:'Diagnostiquer',text:'Identifier les freins SEO, éditoriaux, techniques et de conversion.'},{title:'Prioriser',text:'Transformer l’analyse en plan d’action réaliste : quoi faire, pourquoi et dans quel ordre.'}]" :key="step.title" class="rounded-3xl border border-petrol/15 bg-mist p-7"><p class="text-sm font-semibold text-petrol">0{{ index + 1 }}</p><h3 class="mt-5 text-2xl font-bold">{{ step.title }}</h3><p class="mt-3 leading-7 text-muted">{{ step.text }}</p></article></div></BaseContainer></section>

      <section class="bg-mist py-20 sm:py-28"><BaseContainer><div class="max-w-3xl"><p class="text-sm font-semibold uppercase tracking-[.18em] text-petrol">Le Sprint SEO</p><h2 class="mt-4 text-3xl font-bold tracking-tight sm:text-5xl">Une analyse complète de ton site pour savoir exactement où concentrer tes efforts.</h2><p class="mt-7 text-lg leading-8 text-muted">Pendant le Sprint, j’analyse ton site sous plusieurs angles.</p></div><div class="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3"><article v-for="item in audit" :key="item.title" class="rounded-3xl border border-petrol/15 bg-white/60 p-7"><h3 class="text-2xl font-bold">{{ item.title }}</h3><p class="mt-4 leading-7 text-muted">{{ item.text }}</p></article></div></BaseContainer></section>

      <section class="py-20 sm:py-28"><BaseContainer><div class="grid gap-12 lg:grid-cols-[.8fr_1fr]"><div><p class="text-sm font-semibold uppercase tracking-[.18em] text-petrol">Le résultat</p><h2 class="mt-4 text-3xl font-bold tracking-tight sm:text-5xl">À la fin du Sprint, tu repars avec…</h2><p class="mt-7 text-xl font-semibold leading-8">Et surtout : une vision claire de ce que tu dois faire ensuite.</p></div><ul class="space-y-3 text-lg text-muted"><li v-for="item in deliverables" :key="item" class="flex gap-3"><span class="mt-3 h-1.5 w-1.5 shrink-0 rounded-full bg-petrol" />{{ item }}</li></ul></div></BaseContainer></section>

      <section class="bg-sand-light py-20 sm:py-28"><BaseContainer><div class="max-w-3xl"><p class="text-sm font-semibold uppercase tracking-[.18em] text-petrol">Avant / après</p><h2 class="mt-4 text-3xl font-bold tracking-tight sm:text-5xl">Passer du flou à un plan d’action.</h2></div><div class="mt-12 grid gap-6 lg:grid-cols-2"><div class="rounded-[2rem] border border-petrol/15 bg-white/60 p-8"><h3 class="text-2xl font-bold">Aujourd’hui</h3><ul class="mt-6 space-y-4 text-lg leading-7 text-muted"><li v-for="item in before" :key="item">« {{ item }} »</li></ul></div><div class="rounded-[2rem] bg-petrol-dark p-8 text-sand-light"><h3 class="text-2xl font-bold">Après le Sprint</h3><ul class="mt-6 space-y-4 text-lg leading-7 text-[#d8e1de]"><li v-for="item in after" :key="item" class="flex gap-3"><span class="mt-3 h-1.5 w-1.5 shrink-0 rounded-full bg-[#a9c1bd]" />{{ item }}</li></ul></div></div></BaseContainer></section>

      <section class="bg-petrol-dark py-20 text-center sm:py-28"><BaseContainer><h2 class="mx-auto max-w-3xl text-3xl font-bold tracking-tight text-sand-light sm:text-5xl">Ton site peut devenir un vrai canal d’acquisition.</h2><p class="mx-auto mt-6 max-w-2xl text-lg leading-8 text-[#d8e1de]">Commence par comprendre ce qui bloque et concentre tes efforts là où ils auront le plus d’impact.</p><a :href="props.actionHref" class="mt-9 inline-flex rounded-xl bg-sand px-6 py-3.5 text-sm font-semibold text-petrol-dark transition hover:bg-white">{{ props.actionLabel }}</a></BaseContainer></section>
    </main>
    <PublicFooter tagline="Altruisme Builder — SEO, produit et technique pour transformer ton site en canal d’acquisition." />
  </div>
</template>
